version: 2

sources:
  - name: sap_adw
    description: Fonte SAP de vendas Adventure Works
    schema: sap_adw
    tables:
      - name: product
        columns:
          - name: productid
            tests:
              - unique
              - not_null
      - name: productcategory
        columns: 
          - name: productcategoryid
            tests:
              - unique
              - not_null
      - name: productsubcategory
        columns: 
          - name: productsubcategoryid
            tests:
              - unique
              - not_null
          - name: productcategoryid
            tests:
              - not_null
      - name: salesreason
        columns:
          - name: salesreason
            tests:
            - unique
            - not_null
      - name: person
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null
      - name: customer
        columns:
          - name: customerid
            tests:
              - unique
              - not_null
              
                
              
      
                  
            

